call plug#begin('~/.config/nvim/plugged')
	Plug 'tpope/vim-vinegar'
	Plug 'dracula/vim'
	Plug 'lifepillar/vim-solarized8'
	Plug 'scrooloose/nerdtree'
	Plug 'Xuyuanp/nerdtree-git-plugin'
	Plug 'vim-airline/vim-airline'
	Plug 'vim-airline/vim-airline-themes'
call plug#end()
