if [ -d ~/bin ]; then
  export PATH="$HOME/bin:$PATH"
fi

source ~/.zsh/history.zsh
source ~/.zsh/antigen.zsh
source ~/.zsh/rbenv.zsh
source ~/.zsh/pyenv.zsh
source ~/.zsh/nodenv.zsh
source ~/.zsh/sdkman.zsh
source ~/.zsh/bindkeys.zsh
